---
title: "On rate of HT association"
output: html_notebook
---
This notebook is used to calculate kon of HT association based on HT binding assays.
```{r}
library(plyr)
library(tidyverse)
library(dplyr)
library(data.table)
library(ggplot2)
library(stats)
library(sparklyr)
library(readxl)
library(plotly)
library(openxlsx)
library(gridExtra)
library(ggprism)
library(scales)
library(emojifont)
library(Cairo)
library(ggnewscale)
library(stats)
library(tidymodels)
library(patchwork)
library(formula.tools)
library(data.table)
library(REAT)
library(broom)
```
```{r}
#Links to csv files
url1 <- "https://www.dropbox.com/s/64cc93v4k8yy3lt/20211208_H33342_accumulation_timelapse_transfer_from_old.csv?dl=1"
url2 <- "https://www.dropbox.com/s/di568r38yhduavw/HT_accumulation_demo.csv?dl=1"

# Read and parse to dataframe
 # Data for degradation
df_acc <- fread(url2)
df_acct <- fread(url1)

# Data for accumulation
# Check available columns
colnames(df_acc)
colnames(df_acct)


```
```{r}
df1 <- subset(df_acc ,select = c( Genotype,
                                  HT_Conc_uM,
                                  Repeat,
                                  Time_m,
                                  normed_intensity_ch2
                                  ))
df2 <- subset(df_acct , select =c( NAME,
                                   Genotype,
                                   HT_Conc_uM,
                                   Repeat,
                                   Time_m,
                                   normed_intensity_ch2,
                                   Phenotype))

# Remove time -1 (background measurements)
df_acc <- df_acc[order(df_acc$HT_Conc_uM,df_acc$Time_m),]
df_acct <- df_acct[order(df_acct$HT_Conc_uM,df_acct$Time_m),]
df_acc.WT <- df1[((df1$Time_m >= 0) &
  (df1$Genotype == "WT")&
  (df1$Repeat == 1)),]
df_acc.WT <- df_acc.WT[order(df_acc.WT$HT_Conc_uM,df_acc.WT$Time_m),]
df_acct.WT <- df2[((df2$Time_m >= 0) &
  (df2$Genotype == "WT")&
  (df2$Repeat == 1)),]
df_acct.WT <- df_acct.WT[order(df_acct.WT$HT_Conc_uM,df_acct.WT$Time_m),]

```
Calculate mean and standard deviation for each concentration at each time point
```{r}

df_acc.WT.agg <- df_acc.WT  %>% group_by( HT_Conc_uM , Time_m ) %>%
        summarise(avg_int = mean(normed_intensity_ch2) ,
                  std_int = sd(normed_intensity_ch2))%>%
        mutate( minht    = avg_int - std_int,
                maxht    = avg_int + std_int)
df_acct.WT.agg <- df_acct.WT  %>% group_by(NAME,Phenotype, HT_Conc_uM , Time_m ) %>%
        summarise(avg_int = mean(normed_intensity_ch2) ,
                  std_int = sd(normed_intensity_ch2))%>%
        mutate( minht    = avg_int - std_int,
                maxht    = avg_int + std_int)

```
Plot average of HT intensity as a function of time
```{r}
# Function for point plot 
pointplot <-function(df,x,y,ymin,ymax,color,shape,title,xtitle,ytitle){
  p<-ggplot (df, aes(x, y)) +
        ggnewscale :: new_scale_colour() +
        geom_point(aes(color = as.factor(color),
                       shape = shape),
                   size = 3,
                   stroke = 1.5) +
        geom_line(aes(color = as.factor(color),
                      shape = shape),
                  size = 1,
                  stroke = 1) +
        geom_errorbar(aes(x = x , 
                        y = y , 
                        color = as.factor(color) ,
                        ymin = ymin ,
                        ymax = ymax ),
                    width = 3,
                    size = 1 ) +
        scale_color_prism(palette = "prism_dark") +
        labs(title = title ) +
        scale_x_continuous(name = xtitle,
                           guide = 'prism_offset_minor' ,
                           position = "bottom",
                           limits = c(-2.5,62.5)
                           ) +
        scale_y_continuous(name = ytitle,
                           guide = "prism_offset_minor"
                           ) +
        theme_prism(palette = "prism_dark" ,base_size = 14)
  return(p)
}
```

```{r}
for 
p1 <- pointplot(df = data,
                x = data$Time_m,
                y = data$avg_int,
                ymin = data$minht,
                ymax = data$maxht,
                xtitle = 'Time(m)',
                ytitle = 'Intensity(A.U.)',
                title = 'HT accumulation with WT',
                color = data$HT_Conc_uM,
                shape = NULL)
p1
```
RL = RLmax*(1-exp(-kobs*t))
RLmax = max HT intensity 
RL = y 
RLmax = ymax
t = x
kobs = -(ln(y/ymax)+1)/x
```{r}

kobs <-c()
htconc <-c()
for (i in unique(df_acc.WT$HT_Conc_uM)){
  data <- df_acc.WT[df_acc.WT$HT_Conc_uM == i,]
  x <- data$Time_m
  y <- data$normed_intensity_ch2
  ymax <- max(data$normed_intensity_ch2)
  data <- structure(list(x,y))
  model <- nls(y~ymax*(1-exp(-k*x)), data = data)
  tidy(model)
  sum <- summary(model)
  htconc<-append(htconc,i)
  kobs<-append(kobs,sum$coefficients[1])
  print(sum$coefficients[1])
}
kobsdf <-data.frame(htconc,kobs)
colnames(kobsdf)<-c("HT_Conc_uM", "kobs")
p2 <-ggplot (kobsdf, aes(HT_Conc_uM, kobs)) +
        ggnewscale :: new_scale_colour() +
        geom_point(aes(),
                   size = 3,
                   stroke = 1.5) +
        geom_smooth(method = 'lm')+
        scale_color_prism(palette = "prism_dark") +
        labs(title = "kobs as a function of HT concentration" ) +
        scale_x_continuous(name = "HT Conc.(uM)",
                           guide = 'prism_offset_minor' ,
                           position = "bottom") +
        scale_y_continuous(name = "kobs",
                           guide = "prism_offset_minor"
                           ) +
        theme_prism(palette = "prism_dark" ,base_size = 14)
p2
lregmodel <- coef(lm(formula = kobs~HT_Conc_uM, data = kobsdf))
print(lregmodel)

```
So kon is 0.000236138 (uM/min)



